51- SELECT C.NOME_CLIENTE
FROM CLIENTE C INNER JOIN PEDIDO P ON C.CODIGO_CLIENTE = P.CODIGO_CLIENTE
INNER JOIN VENDEDOR V ON P.CODIGO_VENDEDOR = V.CODIGO_VENDEDOR
WHERE V.NOME_VENDEDOR = 'Antônio'
ORDER BY C.NOME_CLIENTE

52- SELECT C.*
	FROM CLIENTE C INNER JOIN PEDIDO P ON C.CODIGO_CLIENTE = P.CODIGO_CLIENTE
		INNER JOIN ITEM_DO_PEDIDO I ON P.NUM_PEDIDO = I.NUM_PEDIDO
		INNER JOIN PRODUTO PR ON I.CODIGO_PRODUTO = PR.CODIGO_PRODUTO
		WHERE P.PRAZO_ENTREGA > 15 AND
		C.UF = 'RJ' AND
		PR.DESCRICAO_PRODUTO = 'Queijo'
ORDER BY C.NOME_CLIENTE

53- SELECT C.CODIGO_CLIENTE, C.NOME_CLIENTE, P.PRAZO_ENTREGA
FROM CLIENTE C LEFT JOIN PEDIDO P ON C.CODIGO_CLIENTE = P.CODIGO_CLIENTE

54- SELECT V.CODIGO_VENDEDOR, V.NOME_VENDEDOR, P.NUM_PEDIDO
FROM PEDIDO P INNER JOIN VENDEDOR V ON P.CODIGO_VENDEDOR = V.CODIGO_VENDEDOR

55-SELECT PR.CODIGO_PRODUTO, PR.DESCRICAO_PRODUTO,I.NUM_PEDIDO, I.QUANTIDADE
FROM PRODUTO PR LEFT JOIN ITEM_DO_PEDIDO I ON PR.CODIGO_PRODUTO = I.CODIGO_PRODUTO

56- 
SELECT NOME_CLIENTE 
FROM CLIENTE
WHERE CODIGO_CLIENTE IN (SELECT CODIGO_CLIENTE
FROM PEDIDO
WHERE PRAZO_ENTREGA > 25)

57- SELECT *
FROM CLIENTE
WHERE CODIGO_CLIENTE NOT IN (SELECT CODIGO_CLIENTE
							FROM PEDIDO)
58- SELECT DESCRICAO_PRODUTO
FROM PRODUTO
WHERE VAL_UNIT < (SELECT AVG(VAL_UNIT)
				 FROM PRODUTO)

59- SELECT CODIGO_CLIENTE
FROM CLIENTE 
WHERE CODIGO_CLIENTE > (SELECT AVG(PRAZO_ENTREGA)
					   FROM PEDIDO)
60- SELECT NOME_CLIENTE
FROM CLIENTE 
WHERE CODIGO_CLIENTE > (SELECT AVG(PRAZO_ENTREGA)
					   FROM PEDIDO)
61- SELECT DESCRICAO_PRODUTO
FROM PRODUTO
WHERE CODIGO_PRODUTO IN
(SELECT CODIGO_PRODUTO
FROM ITEM_DO_PEDIDO
WHERE QUANTIDADE = (SELECT MAX(QUANTIDADE)
FROM ITEM_DO_PEDIDO))

62- SELECT NOME_CLIENTE
FROM CLIENTE
WHERE CODIGO_CLIENTE IN (SELECT CODIGO_CLIENTE
FROM PEDIDO 
WHERE NUM_PEDIDO IN (SELECT NUM_PEDIDO						
FROM ITEM_DO_PEDIDO									 WHERE QUANTIDADE > (SELECT AVG(QUANTIDADE)
FROM ITEM_DO_PEDIDO)))  